---
# tasks file for myatu.shorewall
- name: Debug OS Version
  debug:
    msg: "distribution: {{ ansible_distribution }}, major_version: {{ ansible_distribution_major_version }}"

- name: Add OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "vars/{{ ansible_distribution }}.yml"
    - "vars/{{ ansible_os_family }}.yml"
    - "vars/defaults.yml"
  tags:
    - configuration
    - packages

- name: Check duplicate tcinterfaces setting
  debug:
    msg: Checking if tcinterfaces is set for both Shorewall and Shorewall6
  failed_when: (shorewall_tcinterfaces is defined) and (shorewall6_tcinterfaces is defined)

- name: Remove incompatible firewall packages
  package:
    name: "{{ item }}"
    state: absent
  with_items: "{{ shorewall_incompatible_packages|default([]) }}"
  when: (shorewall_package_state != "absent")

# Change console logging levels so Shorewall logs don't fill the local console
# See Shorewall FAQ Item 16 for details why https://shorewall.org/FAQ.htm#Logging
- ansible.posix.sysctl:
    name: kernel.printk
    value: '4 4 1 7'
    sysctl_set: yes
    state: present
    reload: yes

- include: shorewall.yml

- include: shorewall6.yml
  when: (shorewall6_enabled|bool)
