---
# tasks file for myatu.shorewall
- name: Debug OS Version
  debug:
    msg: "distribution: {{ ansible_distribution }}, major_version: {{ ansible_distribution_major_version }}"

- name: Ensure single tcinterfaces definition
  assert:
    that: (shorewall_tcinterfaces is undefined) or (shorewall6_tcinterfaces is undefined)
    fail_msg: "only one of shorewall_tcinterfaces and shorewall6_tcinterfaces may be defined"
    quiet: true

- name: Add OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "vars/{{ ansible_distribution }}.yml"
    - "vars/{{ ansible_os_family }}.yml"
    - "vars/defaults.yml"
  tags:
    - configuration
    - packages

- include: sw_run.yml
  when: (shorewall_run|bool) or (shorewall6_run|bool)

- name: Shorewall dead man's switch
  debug:
    msg: "Skipped Shorewall configuration because dead man's switch var 'shorewall_run' is not set to true"
  when: not shorewall_run|bool

- name: Shorewall6 dead man's switch
  debug:
    msg: "Skipped Shorewall6 configuration because dead man's switch var 'shorewall6_run' is not set to true"
  when: not shorewall6_run|bool
